version: '3'
services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  backend:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/backend
      - ./.ssh/id_rsa:/home/developer/.ssh/id_rsa
    environment:
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgres_data:
